### ISSUE TITLE
상품상세보기화면 오류: setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by hanslelee** [Hi-DN/navada-mobile-app#30]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/51855129/195381139-17bad821-6f0a-4564-bad7-9cc86b61445c.png">
상품목록화면에서 상품상세보기화면으로 들어가거나 상품등록후 상품상세보기화면으로 들어갔는데 

위와 같은 오류가 발생하는 것 같습니다! 제쪽에서 혹시 뭘 잘못 합친걸까요...?!ㅠ0ㅠ

화면에서는 문제 없어보이는데 일단 오류가 나오긴 해서 혹시 다른 부분에 문제가 있을까하여 이슈 올립니다😊😊

####
해당 오류
```
════════ Exception caught by foundation library ════════════════════════════════
The following assertion was thrown while dispatching notifications for ProductDetailViewModel:
setState() or markNeedsBuild() called during build.

This _InheritedProviderScope<ProductDetailViewModel?> widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: _InheritedProviderScope<ProductDetailViewModel?>
    value: Instance of 'ProductDetailViewModel'
    listening to value
The widget which was currently being built when the offending call was made was: Consumer<ProductDetailProvider>
    dirty
    dependencies: [_InheritedProviderScope<ProductDetailProvider?>]
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure>
package:flutter/…/widgets/framework.dart:4476
#1      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4491
#2      _InheritedProviderScopeElement.markNeedsNotifyDependents
package:provider/src/inherited_provider.dart:577
#3      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:324
#4      ProductDetailViewModel.setLikeNum
package:navada_mobile_app/…/product_detail/product_detail_view_model.dart:19
#5      ProductDetail._buildProductDetail.<anonymous closure>
package:navada_mobile_app/…/product_detail/product_detail.dart:50
#6      Consumer.buildWithChild
package:provider/src/consumer.dart:179
#7      SingleChildStatelessWidget.build
package:nested/nested.dart:259
#8      StatelessElement.build
package:flutter/…/widgets/framework.dart:4876
#9      SingleChildStatelessElement.build
package:nested/nested.dart:279
#10     ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4806
#11     Element.rebuild
package:flutter/…/widgets/framework.dart:4529
#12     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2659
#13     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:891
#14     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:370
#15     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
#16     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1083
#17     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:997
#21     _invoke (dart:ui/hooks.dart:151:10)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#23     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
The ProductDetailViewModel sending notification was: Instance of 'ProductDetailViewModel'
```

**Comment by minji1110** [comment]
@hanslelee 헉 저도 자세히보니까  setState() or markNeedsBuild() called during build 이렇게 한줄 오류 뜨네요ㅠㅠ 저렇게 길게는 안뜨는데 ide 차이겠죠 그건..? ㅠㅠ
안그래도 상품 상세부분 관련해서 전체 구조 다시 잡아야할 것 같아서, 해당부분 전체 수정후에 저도 다시 테스트해보고 말씀드릴게요!! ㅠㅠ

**Comment by minji1110** [comment]
좋아요의 개수와 여부에 대한 정보는 Provider에 존재하는데, 이를 다시 viewModel로 넘겨주려다보니 생긴 오류로 보임
-> 두 항목을 Provider에서 관리하도록 수정함으로써 해결
